### ISSUE TITLE
Estoy huerfanito y necesito casa

### ISSUE THREAD

**Issue by lasr21** [BoSicle/conference#2]
Pinerle un server a mozillaneciencias ya sea en Github 
pages o en mozilla-mexico

**Comment by odinm** [comment]
Ya se van a realizar todas las actividades que conlleva en el servidor de Mozilla México, en cuanto este les avisamos. 

Saludos,

**Comment by mautematico** [comment]
Es necesario que el sitio web refleje **siempre** los cambios más recientes del repositorio, con todas sus dependencias, etcétera.

¿En el servidor donde está Mozilla México habrá un cronjob o algo similar que continuamente haga deploy del HEAD del master de este repositorio, incluyendo el paso de instalar las dependencias?

**Comment by lasr21** [comment]
Eso estaría cool un cron al HEAD, cada semana es tiempo suficiente para buscar si hay un un commit nuevo en head?

**Comment by mautematico** [comment]
Cada semana me parece demasiado tiempo, en comparación con _siempre_.
Estaríamos hablando, a lo más, de **horas**, pensando en el tiempo de vida de un caché.

Hay que tener en cuenta que _revisar si hay nuevos commits_ prácticamente no cuesta nada, comparado por ejemplo con renovar el caché de un blog de wordpress.

Creo que lo ideal sería implementar algo parecido a los webhooks, pero sospecho que será inviable.

**Comment by odinm** [comment]
Yo no lo aplicaría al viva México, porque antes de subir a producción se deben de probar los cambios, antes de bajarlos al servidor producción, por lo que no lo sincronizaría, correjanme si estoy diciendo una tontería jaja

Aparte Cronos no pudo bajar el proyecto, le mando problemas, marcando que no esta la llave.

**Comment by siclemx** [comment]
Ya están los cambios de DNS en el dominio :8ball:

**Comment by mautematico** [comment]
¿Cuál llave?

> Aparte Cronos no pudo bajar el proyecto, le mando problemas, marcando que no esta la llave.

**Comment by tuxlan** [comment]
@mautematico, @odinm se refiere a la llave pública del server, si no existe genero una y lo agrego a la cuenta de github de mozillamexico

**Comment by mautematico** [comment]
@mozillamexico no es una cuenta, sino una organización. Supongo que el procedimiento será usar el par público-privado de alguno de los que tienen acceso al servidor y a la organización.
O bien, yo puedo agregar la llave pública en el apartado `deploy keys`, si quieren eso, dejen la llave pública como respuesta a este issue.

De forma paralela voy a hacer deploy en github pages.

**Comment by tuxlan** [comment]
El procedimiento debe ser el mismo, aunque yo cloné el proyecto en el servidor sin ningún problema de llaves. Se puede deber a que Cronos lo clonó con otro usuario @odinm

**Comment by odinm** [comment]
@tuxlan hay que preguntarle, le pedí que se agregara pero no lo ha hecho. 

@BoSicle tons ¿ya se ve el sitio? Si no para decirle. 

@mautematico no tiene caso tener el sitio en dos lugares ¿o si?

**Comment by cron0s** [comment]
hola buenas noches.

**Comment by cron0s** [comment]
ya esta configurado el sitio y todo, solo falta que respondan los DNS http://who.is/whois/mozillaenciencias.com

**Comment by odinm** [comment]
Gracias @cron0s xD quedo en la carpeta ciencias ¿verdad? @tuxlan todo tuyo jeje

**Comment by siclemx** [comment]
Ya están los DNS http://who.is/whois/mozillaenciencias.com :earth_americas:
